language: node_js
node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "12"
   - "10"
   - "8"


before_install: if [[ `node -v` != 12* ]]; then npm i -g npm@6.13.4; fi

script:
   - node --version
   - npm --version
   - grunt standards
   - commitlint-travis
   - grunt clean build
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
