language: node_js
node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "12"
   - "10"

before_install: npm i -g npm@6.13.4

script:
   - node --version
   - npm --version
   - grunt standards
   - commitlint-travis
   - grunt clean build
   - npm test

jobs:
  include:
#     # Define the release stage that runs semantic-release
   - stage: release
      node_js: 12
      deploy:
         provider: script
         skip_cleanup: true
         script:
            - npm run semantic-release
         on:
            tags: true

# For code coverage:
# after_success:
#    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
